version: '3.8'
services:
  db:
    image: postgres:14.15-alpine3.21
    container_name: urlshortener_db
    environment:
      POSTGRES_USER: urlshortener
      POSTGRES_PASSWORD: urlshortenerpassword
      POSTGRES_DB: urlshortener
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
